//! Network throughput, from the interface table.
//!
//! `GetIfTable2` returns one `MIB_IF_ROW2` per logical and physical interface,
//! each carrying cumulative `InOctets` and `OutOctets` since the interface came
//! up. It needs no handle, no privilege and no COM, and it is available from
//! Windows Vista onwards — so it is available everywhere LocalDocks runs.
//!
//! Measured at 0.90 ms for the 50 interfaces on the development machine, which
//! makes it the most expensive of the four telemetry providers and still an
//! order of magnitude cheaper than the process scan it rides beside.
//!
//! # What is deliberately not here
//!
//! **Per-process network attribution.** It is the number a developer actually
//! wants beside a service — *which* of my servers is talking — and it is not
//! reachable this way. It needs an ETW session on
//! `Microsoft-Windows-Kernel-Network`, and starting one needs elevation.
//! LocalDocks does not elevate, so V1 reports machine-wide throughput and
//! docs/ROADMAP.md records the per-process form as deferred with that reason.
//!
//! # Filtering
//!
//! The table is mostly not interesting. The development machine reports 50
//! rows, of which three are real: an Ethernet adapter, a Wi-Fi Direct virtual
//! adapter and a disconnected Wi-Fi radio. The rest are tunnels, WFP filter
//! interfaces and adapters that are not present. Three rules cut it down, and
//! each is a property Windows reports rather than a guess about a name:
//!
//!   * **Operational.** `IfOperStatusUp`. A disconnected adapter's counters are
//!     frozen, so including it adds a row that is always zero.
//!   * **Not loopback.** Loopback traffic is not network throughput, and on a
//!     development machine it is most of the traffic.
//!   * **Not a filter interface.** WFP callout interfaces mirror the traffic of
//!     the adapter they sit on, so counting them doubles every byte.

use windows::Win32::NetworkManagement::IpHelper::{
    FreeMibTable, GetIfTable2, IF_TYPE_SOFTWARE_LOOPBACK, MIB_IF_TABLE2,
};
use windows::Win32::NetworkManagement::Ndis::IfOperStatusUp;

/// `FilterInterface`, the second bit of `MIB_IF_ROW2`'s flags bitfield.
///
/// The `windows` crate exposes the anonymous bitfield as a raw `u8` rather than
/// generating accessors, so the bit order comes from the SDK header:
/// `HardwareInterface` is bit 0 and `FilterInterface` is bit 1.
const FILTER_INTERFACE: u8 = 1 << 1;

use crate::logic::telemetry::RawInterface;

/// Every interface whose counters are worth reading.
///
/// `None` only if the table itself could not be read, which would mean the
/// networking stack is unavailable. An empty list is a valid answer — a machine
/// with every adapter disabled has no throughput to report, and that is a
/// measurement rather than a failure.
pub fn interfaces() -> Option<Vec<RawInterface>> {
    let mut table: *mut MIB_IF_TABLE2 = std::ptr::null_mut();

    // SAFETY: `table` is a live out-pointer; on success Windows allocates the
    // table and `FreeMibTable` below releases it on every path.
    let status = unsafe { GetIfTable2(&mut table) };
    if status.is_err() || table.is_null() {
        log::debug!("GetIfTable2 failed: {status:?}");
        return None;
    }

    // SAFETY: the call succeeded, so `table` points at a MIB_IF_TABLE2 whose
    // `Table` field is a `NumEntries`-long array.
    let rows = unsafe {
        let count = (*table).NumEntries as usize;
        std::slice::from_raw_parts((*table).Table.as_ptr(), count)
    };

    let mut interfaces = Vec::new();
    for row in rows {
        if row.OperStatus != IfOperStatusUp {
            continue;
        }
        if row.Type == IF_TYPE_SOFTWARE_LOOPBACK {
            continue;
        }
        // A WFP filter interface mirrors the adapter beneath it. The bitfield
        // accessor is generated by the windows crate from the anonymous
        // bitfield in MIB_IF_ROW2.
        if row.InterfaceAndOperStatusFlags._bitfield & FILTER_INTERFACE != 0 {
            continue;
        }

        interfaces.push(RawInterface {
            // The LUID, not the index: Windows reassigns interface indices,
            // and a reassigned key would silently pair one adapter's previous
            // counters with another's current ones.
            luid: unsafe { row.InterfaceLuid.Value },
            name: wide_to_string(&row.Alias),
            description: wide_to_string(&row.Description),
            in_octets: row.InOctets,
            out_octets: row.OutOctets,
            // Some adapters report a sentinel rather than a speed.
            link_speed_bits_per_sec: (row.ReceiveLinkSpeed > 0 && row.ReceiveLinkSpeed != u64::MAX)
                .then_some(row.ReceiveLinkSpeed),
        });
    }

    // SAFETY: `table` came from a successful GetIfTable2 and is freed once.
    unsafe { FreeMibTable(table as *const _) };

    Some(interfaces)
}

/// A fixed-width wide field to a String, stopping at the first NUL.
///
/// `Alias` and `Description` are fixed arrays padded with NULs rather than
/// NUL-terminated strings, so decoding the whole array would append the
/// padding.
fn wide_to_string(field: &[u16]) -> String {
    let end = field.iter().position(|&c| c == 0).unwrap_or(field.len());
    String::from_utf16_lossy(&field[..end]).trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn the_machine_reports_interfaces_with_stable_identities() {
        let first = interfaces().expect("GetIfTable2 is available on every Windows build");

        // A machine with no operational adapter is legitimate, so this asserts
        // the shape rather than a count.
        let luids: HashSet<u64> = first.iter().map(|i| i.luid).collect();
        assert_eq!(luids.len(), first.len(), "LUIDs must be unique");

        for i in &first {
            assert!(!i.name.is_empty(), "an interface must have a name");
            assert!(
                !i.name.contains('\0'),
                "NUL padding leaked into {:?}",
                i.name
            );
            assert!(!i.description.contains('\0'));
        }

        // The identity must be stable across calls, or every tick would look
        // like every interface disappeared and reappeared.
        let second = interfaces().unwrap();
        let again: HashSet<u64> = second.iter().map(|i| i.luid).collect();
        assert_eq!(luids, again, "interface identities changed between calls");
    }

    #[test]
    fn counters_are_cumulative_and_never_go_backwards() {
        let first = interfaces().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(150));
        let second = interfaces().unwrap();

        for a in &first {
            let Some(b) = second.iter().find(|i| i.luid == a.luid) else {
                continue; // an interface may legitimately drop mid-test
            };
            assert!(
                b.in_octets >= a.in_octets,
                "{}: octets went backwards",
                a.name
            );
            assert!(
                b.out_octets >= a.out_octets,
                "{}: octets went backwards",
                a.name
            );
        }
    }

    /// Loopback is where a development machine's traffic mostly goes, so
    /// including it would make the reading meaningless.
    #[test]
    fn loopback_and_filter_interfaces_are_excluded() {
        for i in interfaces().unwrap() {
            assert!(
                !i.description.to_lowercase().contains("loopback"),
                "loopback leaked through: {}",
                i.description
            );
        }
    }
}
